name: weather_app
description: "A simple weather app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  intl: ^0.20.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/weathers/